/**
 * Export utilities for LLM Council conversations.
 */

/**
 * Export conversation to Markdown format.
 * @param {Object} conversation - The conversation object
 */
export function exportToMarkdown(conversation) {
  const markdown = generateMarkdown(conversation);
  const filename = sanitizeFilename(conversation.title || 'conversation') + '.md';
  downloadFile(markdown, filename, 'text/markdown');
}

/**
 * Export conversation to JSON format.
 * @param {Object} conversation - The conversation object
 */
export function exportToJSON(conversation) {
  const json = JSON.stringify(conversation, null, 2);
  const filename = sanitizeFilename(conversation.title || 'conversation') + '.json';
  downloadFile(json, filename, 'application/json');
}

/**
 * Generate Markdown content from a conversation.
 * @param {Object} conversation - The conversation object
 * @returns {string} Markdown content
 */
function generateMarkdown(conversation) {
  let md = `# ${conversation.title || 'Conversation'}\n\n`;
  md += `*Exported: ${new Date().toLocaleString()}*\n\n`;
  md += `---\n\n`;

  for (const msg of conversation.messages || []) {
    if (msg.role === 'user') {
      md += `## User Question\n\n`;
      md += `${msg.content}\n\n`;
    } else {
      // Stage 1: Individual Responses
      if (msg.stage1 && msg.stage1.length > 0) {
        md += `## Stage 1: Individual Responses\n\n`;
        for (const resp of msg.stage1) {
          const modelName = resp.model.split('/')[1] || resp.model;
          md += `### ${modelName}\n\n`;
          md += `${resp.response}\n\n`;
        }
      }

      // Stage 2: Peer Rankings
      if (msg.stage2 && msg.stage2.length > 0) {
        md += `## Stage 2: Peer Rankings\n\n`;
        for (const ranking of msg.stage2) {
          const modelName = ranking.model.split('/')[1] || ranking.model;
          md += `### ${modelName}'s Evaluation\n\n`;
          md += `${ranking.ranking}\n\n`;

          // Include parsed ranking if available
          if (ranking.parsed_ranking && ranking.parsed_ranking.length > 0) {
            md += `**Extracted Ranking:** ${ranking.parsed_ranking.join(' > ')}\n\n`;
          }
        }
      }

      // Stage 3: Final Synthesis
      if (msg.stage3) {
        md += `## Stage 3: Final Synthesis\n\n`;
        const chairmanName = msg.stage3.model?.split('/')[1] || msg.stage3.model || 'Unknown';
        md += `*Chairman: ${chairmanName}*\n\n`;
        md += `${msg.stage3.response || ''}\n\n`;
      }

      md += `---\n\n`;
    }
  }

  md += `\n*Generated by LLM Council*\n`;

  return md;
}

/**
 * Sanitize a string for use as a filename.
 * @param {string} name - The original name
 * @returns {string} Sanitized filename
 */
function sanitizeFilename(name) {
  return name
    .replace(/[<>:"/\\|?*]/g, '') // Remove invalid characters
    .replace(/\s+/g, '_')          // Replace spaces with underscores
    .substring(0, 50);              // Limit length
}

/**
 * Trigger a file download in the browser.
 * @param {string} content - File content
 * @param {string} filename - Name of the file
 * @param {string} mimeType - MIME type of the file
 */
function downloadFile(content, filename, mimeType) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
